// apps/react/src/components/Grid.tsx
import { useMemo } from "react";
import { useControlPanelContext } from "../context/ControlPanel/useControlPanelContext";
import { getGridSize } from "@app/utils";
import { Cell } from "./Cell";

import classes from "@app/styles/Grid.module.css";

export const Grid = () => {
  const { amount, gap } = useControlPanelContext();

  const cells = useMemo(
    () =>
      Array.from(
        { length: amount },
        (_, i) => <Cell key={i} index={i} />,
      ),
    [amount],
  );

  const { cols, rows } = getGridSize(amount);

  const style: React.CSSProperties = {
    gridTemplateColumns: `repeat(${cols}, minmax(0, 1fr))`,
    gridTemplateRows: `repeat(${rows}, minmax(0, 1fr))`,
    gap: `${gap}rem`,
  };

  return (
    <div
      className={classes.grid}
      style={style}
    >
      {cells}
    </div>
  );
};

// apps/solid/src/components/Grid.tsx
import { createMemo, Index } from "solid-js";
import { getGridSize } from "@app/utils";

import { settings } from "../store/settings";
import { Cell } from "./Cell";

import classes from "@app/styles/Grid.module.css";
import { gap } from "../store/gap";

export const Grid = () => {
  const gridSettings = createMemo(() => getGridSize(settings.amount));

  return (
    <div
      class={classes.grid}
      style={{
        "grid-template-columns":
          `repeat(${gridSettings().cols}, minmax(0, 1fr))`,
        "grid-template-rows": `repeat(${gridSettings().rows}, minmax(0, 1fr))`,
        gap: `${gap()}rem`,
      }}
    >
      <Index each={Array.from({ length: settings.amount })}>
        {(_, index) => <Cell index={index} />}
      </Index>
    </div>
  );
};
