// apps/solid/src/App.tsx
import classes from "@app/styles/App.module.css";
import { ControlPanel } from "./components/ControlPanel";
import { Grid } from "./components/Grid";
import { wsClient } from "./services/wsClient";
import { createEffect, onCleanup, onMount } from "solid-js";
import { settings } from "./store/settings";

export const App = () => {
  createEffect(() => {
    wsClient.updateSettings({ amount: settings.amount, speed: settings.speed });
  });
  onMount(() => wsClient.connect());
  onCleanup(() => wsClient.disconnect());

  return (
    <div class={classes.app}>
      <ControlPanel />
      <Grid />
    </div>
  );
};

// apps/react/src/App.tsx
import { AppProviders } from "./AppProviders/AppProviders";
import { ControlPanel } from "./components/ControlPanel";
import { Grid } from "./components/Grid";
import { useWsClient } from "./hooks/useWsClient";
import classes from "@app/styles/App.module.css";

export const App = () => {
  useWsClient();

  return (
    <AppProviders>
      <div className={classes.app}>
        <ControlPanel />
        <Grid />
      </div>
    </AppProviders>
  );
};
