// apps/react/src/main.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { App } from "./App.tsx";

import "normalize.css";
import "@app/styles/global.css";

const root = document.getElementById("root");

if (!root) throw new Error("Missing #root element in HTML");

createRoot(root).render(
  <StrictMode>
    <App />
  </StrictMode>,
);

// apps/solid/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web";
import "solid-devtools";

import "./index.css";
import "normalize.css";
import { App } from "./App";

const root = document.getElementById("root");

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    "Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?",
  );
}

render(() => <App />, root!);
